esphome:
  name: esp32-clean

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

status_led:
  pin: GPIO08

i2c:
  - id: bus_a
    sda: GPIO5
    scl: GPIO6
    frequency: 400kHz
    scan: true

display:
  - platform: ssd1306_i2c
    model: "SSD1306 72x40"
    i2c_id: bus_a
    address: 0x3C
    id: oled_display
    rotation: 0
    # update_interval: 1s  
    offset_y: 0
    offset_x: 0
    # invert: false  # Optional
    pages:
      - id: page0
        lambda: |-
          // 64x32 mono bitmap (inverted), MSB-first per row. '1' = white pixel on black background.
          static const uint8_t IMG[] = {
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
            0x00, 0x00, 0x00, 0x00, 0x00, 0x07, 0x80, 0x40, 0x00, 0x00, 0x00, 0x02, 
            0x00, 0x0F, 0x81, 0x80, 0x00, 0x00, 0x00, 0x03, 0x10, 0x1F, 0xC1, 0x80, 
            0x00, 0x00, 0x00, 0x03, 0x90, 0x27, 0xE1, 0x80, 0x3F, 0x41, 0xFF, 0x01, 
            0xE0, 0x01, 0xE1, 0x80, 0x3F, 0xC3, 0xFF, 0x81, 0xF8, 0x00, 0x63, 0x00, 
            0x30, 0xC7, 0xFF, 0xC0, 0xE0, 0x00, 0x30, 0x06, 0x30, 0xC7, 0x83, 0xE0, 
            0x7F, 0xF1, 0xF0, 0x1E, 0x7F, 0x8F, 0x01, 0xE0, 0x3F, 0xF2, 0xE0, 0x7C, 
            0x7F, 0x8F, 0x10, 0xE0, 0x00, 0x00, 0x06, 0x78, 0x60, 0xCF, 0x38, 0xE0, 
            0x00, 0x00, 0x00, 0x00, 0x61, 0xDE, 0x38, 0x20, 0x00, 0x00, 0x00, 0x00, 
            0xFF, 0x9F, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFE, 0x07, 0x83, 0xC7, 
            0x3F, 0x07, 0xFC, 0x7E, 0x00, 0x03, 0x8D, 0xC6, 0x3F, 0xC3, 0xF8, 0xFE, 
            0x3C, 0x63, 0x98, 0x06, 0x31, 0xE6, 0x01, 0xC0, 0x3C, 0xF3, 0xDC, 0x0E, 
            0x70, 0xE6, 0x01, 0xC0, 0x3C, 0x67, 0x9F, 0x8E, 0x70, 0x67, 0xF1, 0xF8, 
            0x1C, 0x07, 0x8F, 0xCC, 0x60, 0xE7, 0xF0, 0x7E, 0x1F, 0x1F, 0x81, 0xCC, 
            0x60, 0xCE, 0x00, 0x0E, 0x0F, 0xFF, 0x31, 0xCC, 0x77, 0x80, 0x01, 0x0E, 
            0x07, 0xFE, 0x7F, 0x9C, 0xFF, 0x0F, 0x73, 0xFC, 0x03, 0xF8, 0x0F, 0x1C, 
            0x78, 0x0F, 0xF0, 0xF0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
            0x00, 0x00, 0x00, 0x00, 
          };

          const int IMG_W = 64;
          const int IMG_H = 32;
          const int BYTES_PER_ROW = (IMG_W + 7) / 8;

          int x0 = 5; // adjust or center as needed
          int y0 = -5;

          it.fill(COLOR_OFF);

          for (int y = 0; y < IMG_H; y++) {
            for (int bx = 0; bx < BYTES_PER_ROW; bx++) {
              uint8_t v = IMG[y*BYTES_PER_ROW + bx];
              for (int b = 0; b < 8; b++) {
                int x = bx*8 + b;
                if (x >= IMG_W) break;
                bool on = (v & (0x80 >> b));
                if (on) { it.draw_pixel_at(x0 + x, y0 + y, COLOR_ON); }
              }
            }
          }

      - id: page1
        lambda: |-
          it.print(0, 14, id(roboto_black_big), "B");
          it.print(8, 14, id(roboto_black_big), "Z");
          it.print(16, 14, id(roboto_black_big), "'");
          it.print(17, 14, id(roboto_black_big), "s");
          it.print(25, 12, id(roboto_black_10), "ESPHome");
          it.print(25, 20, id(roboto_black_10), "Workshop");
          // it.print(64, 29, id(roboto_black_10), "p");

interval:
  - interval: 3s
    then:
      - display.page.show_next: oled_display
      - component.update: oled_display

font:
  - id: roboto_black_10
    file: "gfonts://Roboto"
    size: 10
  - id: roboto_black_big
    file: "gfonts://Roboto"
    size: 15