esphome:
  name: esp32-complete

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

status_led:
  pin: GPIO08

i2c:
  - id: bus_a
    sda: GPIO5
    scl: GPIO6
    frequency: 400kHz
    scan: true

sensor:
  - platform: aht10 # Base class
    variant: AHT20 # AHT 20 and 30 both
    i2c_id: bus_a
    address: 0x38
    temperature:
      name: "Temperature"
      id: temp
    humidity:
      name: "Humidity"
      id: humidity
    update_interval: 3s

time:
  - platform: sntp
    id: sntp_time
    timezone: Australia/Sydney
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org

display:
  - platform: ssd1306_i2c
    model: "SSD1306 72x40"
    i2c_id: bus_a
    address: 0x3C
    id: oled_display
    rotation: 0
    # update_interval: 1s  
    offset_y: 0
    offset_x: 0
    # invert: false  # Optional
    pages:
      - id: page0
        lambda: |-
          // 72x40 mono bitmap (re-inverted), MSB-first per row. '1' = white pixel on black background.
          static const uint8_t IMG[] = {
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0C, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x3E, 0x01, 0x80, 0x00, 0x00, 0x00, 0x00, 0x61, 0x00,
            0x7F, 0x02, 0x80, 0x00, 0x00, 0x00, 0x00, 0x31, 0x00, 0xFF, 0x01, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x39, 0x81, 0xFF, 0x85, 0x00, 0x1F, 0x00, 0x3F,
            0xC0, 0x1E, 0x80, 0x0F, 0x85, 0x00, 0x3F, 0xF0, 0xFF, 0xF0, 0x1F, 0x80,
            0x03, 0xC7, 0x00, 0x38, 0xF0, 0xFF, 0xF8, 0x0F, 0x40, 0x00, 0xC4, 0x02,
            0x38, 0x71, 0xFF, 0xFC, 0x0E, 0x00, 0x06, 0xF0, 0x0E, 0x38, 0xE3, 0xE0,
            0x7C, 0x03, 0xFF, 0xC7, 0x80, 0x3E, 0x7F, 0xC3, 0xC0, 0x3E, 0xC9, 0xFF,
            0x89, 0x80, 0xFC, 0x7F, 0xE7, 0xC6, 0x3E, 0x00, 0x00, 0x00, 0x1C, 0xF8,
            0x70, 0xE7, 0x8F, 0x3E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x70, 0xE7, 0x8F,
            0x1E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7F, 0xEF, 0xC4, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0xFF, 0x87, 0xC0, 0x30, 0x00, 0x00, 0x00, 0x00, 0x38,
            0x00, 0x01, 0xE0, 0x7C, 0xF3, 0xFC, 0x1F, 0xF0, 0xFE, 0x00, 0x00, 0xF3,
            0xB8, 0xE3, 0xFE, 0x1F, 0xF1, 0xFE, 0x3E, 0x39, 0xF7, 0x00, 0xE3, 0x8F,
            0x18, 0x03, 0x80, 0x3C, 0x79, 0xF7, 0x00, 0xE3, 0x07, 0x38, 0x03, 0xC0,
            0x1C, 0x31, 0xE7, 0xF0, 0xE7, 0x03, 0x3F, 0xE3, 0xF0, 0x1E, 0x01, 0xE3,
            0xF8, 0xC7, 0x07, 0x3F, 0xE1, 0xFC, 0x1F, 0x03, 0xE0, 0x39, 0xC3, 0x07,
            0x38, 0x00, 0x1E, 0x0F, 0xDF, 0xCC, 0x39, 0xC7, 0x0E, 0x30, 0x02, 0x0E,
            0x07, 0xFF, 0xDE, 0x39, 0xC7, 0xFC, 0x00, 0x67, 0x1C, 0x03, 0xFF, 0x0F,
            0xF1, 0xCF, 0xF8, 0x7F, 0xC7, 0xFC, 0x01, 0xFC, 0x03, 0xC1, 0x87, 0xC0,
            0x7F, 0xC1, 0xF0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
          };

          const int IMG_W = 72;
          const int IMG_H = 40;
          const int BYTES_PER_ROW = (IMG_W + 7) / 8;

          int x0 = 0; // adjust or center as needed
          int y0 = 0;

          for (int y = 0; y < IMG_H; y++) {
            for (int bx = 0; bx < BYTES_PER_ROW; bx++) {
              uint8_t v = IMG[y*BYTES_PER_ROW + bx];
              for (int b = 0; b < 8; b++) {
                int x = bx*8 + b;
                if (x >= IMG_W) break;
                bool on = (v & (0x80 >> b));
                if (on) { it.draw_pixel_at(x0 + x, y0 + y); }
              }
            }
          }
      - id: page1
        lambda: |-
          it.print(0, -2, id(roboto_black_12), "BSides Syd");
          it.strftime(15, 28, id(roboto_black_12), "%H:%M:%S", id(sntp_time).now());
      - id: page2
        lambda: |-
          it.printf(0, 8, id(roboto_black_12), "T %.1f°C", id(temp).state);
          it.printf(0, 18, id(roboto_black_12), "H %.1f%%", id(humidity).state);

font:
  - id: roboto_black_12
    file: "gfonts://Roboto"
    size: 12

interval:
  - interval: 3s
    then:
      - display.page.show_next: oled_display
      - component.update: oled_display